### ISSUE TITLE
multiples media  querys with the same size

### ISSUE THREAD

**Issue by nimplay** [renercrows/Desktop-Portdolio#5]
Hello maximiliano kindly let me point out that he has opened multiple media queries with the same measure. 
Your code would be more optimized if it included all variations of a media query measure in the same section.
The reason for making this modification is to avoid loading problems when implementing your website.
yours sincerely nimrod

**Comment by Nyame-Wolf** [comment]
This is really good work. Your site works well and it has really replicated the figma design. Good job. However, i think it would be important to avoid using too many media query in line with DRY. All lines you have media queries can be reduced to two media queries only.
